### ISSUE TITLE
Peer-Review ww4-module2

### ISSUE THREAD

**Issue by daudi13** [Sboursen/Leaderboard#7]
Good job @Sboursen for going the extra mile with your project. we took a look a look at your work and we have to appreciate;
- your colorful styling
- making the project responsive for both desktop and mobile displays
- Ensuring all the APIs work as required
### However we found a few issues in your project that could use a little fixing

- [x] Please consider adding a notification/ alert when a user adds a new score
- [x] Please consider adding a margin-bottom to your body
- [x] optionally you can add a display showing the number of scores available for viewing

Otherwise, keep it up!!

**Comment by Sboursen** [comment]
Hi @daudi13 :wave: 
Thank you for your contribution.
I'll make sure to take them into account for the next release.
Cheers
